import type { Species } from '../types';

export const RANGIROA_SPECIES: Species[] = [
  {
    id: '1', name_common_fr: 'Grand Dauphin', name_common_en: 'Bottlenose Dolphin', name_scientific: 'Tursiops truncatus',
    category: 'mammal', habitat: ['lagoon', 'ocean'],
    description: 'Le grand dauphin peuple les eaux cristallines de Rangiroa, souvent observé dans le Lagon bleu et à Tiputa Pass.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tursiops_truncatus_01.jpg/1200px-Tursiops_truncatus_01.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tursiops_truncatus_01.jpg/400px-Tursiops_truncatus_01.jpg',
    conservation_status: 'LC', is_endemic: false,
    fun_fact: 'Les dauphins de Rangiroa surfent régulièrement sur les vagues du Tiputa Pass lors des courants entrants.',
    locations: [{ id: 'l1', species_id: '1', latitude: -14.9950, longitude: -147.6323, name: 'Tiputa Pass' }, { id: 'l2', species_id: '1', latitude: -14.9700, longitude: -147.7500, name: 'Lagon Bleu' }],
    inaturalist_id: 42888, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2', name_common_fr: 'Requin Gris de Récif', name_common_en: 'Grey Reef Shark', name_scientific: 'Carcharhinus amblyrhynchos',
    category: 'shark', habitat: ['reef', 'ocean'],
    description: 'Le requin gris de récif est omniprésent dans les passes de Rangiroa. Il patrouille les tombants coralliens à la recherche de proies.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Carcharhinus_amblyrhynchos.jpg/1200px-Carcharhinus_amblyrhynchos.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Carcharhinus_amblyrhynchos.jpg/400px-Carcharhinus_amblyrhynchos.jpg',
    conservation_status: 'EN', is_endemic: false,
    fun_fact: 'Des centaines de requins gris se rassemblent à Tiputa Pass pour se nourrir pendant les courants entrants.',
    locations: [{ id: 'l3', species_id: '2', latitude: -14.9950, longitude: -147.6323, name: 'Tiputa Pass' }, { id: 'l4', species_id: '2', latitude: -15.0100, longitude: -147.7000, name: 'Avatoru Pass' }],
    inaturalist_id: 43968, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3', name_common_fr: 'Raie Manta', name_common_en: 'Giant Manta Ray', name_scientific: 'Mobula birostris',
    category: 'ray', habitat: ['ocean', 'reef'],
    description: 'La raie manta géante, pouvant atteindre 7 mètres d\'envergure, se nourrit de plancton en pleine eau.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Manta_birostris-edit2.jpg/1200px-Manta_birostris-edit2.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Manta_birostris-edit2.jpg/400px-Manta_birostris-edit2.jpg',
    conservation_status: 'VU', is_endemic: false,
    fun_fact: 'La raie manta possède le plus grand cerveau de tous les poissons, avec une capacité d\'apprentissage remarquable.',
    locations: [{ id: 'l5', species_id: '3', latitude: -14.9950, longitude: -147.6323, name: 'Tiputa Pass' }],
    inaturalist_id: 60234, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4', name_common_fr: 'Napoléon', name_common_en: 'Humphead Wrasse', name_scientific: 'Cheilinus undulatus',
    category: 'fish', habitat: ['reef', 'lagoon'],
    description: 'Le napoléon, reconnaissable à sa bosse frontale et ses lèvres charnues, peut vivre plus de 30 ans.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Cheilinus_undulatus_Courtenay-Latimer.jpg/1200px-Cheilinus_undulatus_Courtenay-Latimer.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Cheilinus_undulatus_Courtenay-Latimer.jpg/400px-Cheilinus_undulatus_Courtenay-Latimer.jpg',
    conservation_status: 'EN', is_endemic: false,
    fun_fact: 'Le napoléon peut changer de sexe : certaines femelles deviennent mâles en vieillissant.',
    locations: [{ id: 'l6', species_id: '4', latitude: -15.0100, longitude: -147.7000, name: 'Avatoru Pass' }],
    inaturalist_id: 44025, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5', name_common_fr: 'Tortue Verte', name_common_en: 'Green Sea Turtle', name_scientific: 'Chelonia mydas',
    category: 'mammal', habitat: ['lagoon', 'reef'],
    description: 'La tortue verte est fréquente dans les eaux de Rangiroa. Elle se nourrit d\'herbiers marins et de coraux.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Green_Sea_Turtle_grazing_seagrass.jpg/1200px-Green_Sea_Turtle_grazing_seagrass.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Green_Sea_Turtle_grazing_seagrass.jpg/400px-Green_Sea_Turtle_grazing_seagrass.jpg',
    conservation_status: 'EN', is_endemic: false,
    fun_fact: 'Les tortues vertes peuvent rester en apnée jusqu\'à 7 heures lors du sommeil.',
    locations: [{ id: 'l7', species_id: '5', latitude: -14.9700, longitude: -147.7500, name: 'Lagon Bleu' }, { id: 'l8', species_id: '5', latitude: -15.0000, longitude: -147.6800, name: 'Les Sables Roses' }],
    inaturalist_id: 46861, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6', name_common_fr: 'Aigle de Mer Tachété', name_common_en: 'Spotted Eagle Ray', name_scientific: 'Aetobatus narinari',
    category: 'ray', habitat: ['lagoon', 'ocean'],
    description: 'La raie aigle tachétée se distingue par ses magnifiques taches blanches sur fond sombre.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Aetobatus_narinari.jpg/1200px-Aetobatus_narinari.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Aetobatus_narinari.jpg/400px-Aetobatus_narinari.jpg',
    conservation_status: 'VU', is_endemic: false,
    fun_fact: 'La raie aigle peut sauter hors de l\'eau et parcourir plusieurs mètres dans les airs.',
    locations: [{ id: 'l9', species_id: '6', latitude: -14.9950, longitude: -147.6323, name: 'Tiputa Pass' }],
    inaturalist_id: 47232, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '7', name_common_fr: 'Murène Géante', name_common_en: 'Giant Moray', name_scientific: 'Gymnothorax javanicus',
    category: 'fish', habitat: ['reef'],
    description: 'La murène géante peut atteindre 3 mètres. Elle se cache dans les anfractuosités du récif.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Giant_Moray_Gymnothorax_javanicus.jpg/1200px-Giant_Moray_Gymnothorax_javanicus.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Giant_Moray_Gymnothorax_javanicus.jpg/400px-Giant_Moray_Gymnothorax_javanicus.jpg',
    conservation_status: 'LC', is_endemic: false,
    fun_fact: 'La murène possède deux mâchoires : une pour saisir les proies et une pharyngienne pour les avaler.',
    locations: [{ id: 'l10', species_id: '7', latitude: -15.0100, longitude: -147.7000, name: 'Avatoru Pass' }],
    inaturalist_id: 52869, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '8', name_common_fr: 'Barracuda Chevron', name_common_en: 'Chevron Barracuda', name_scientific: 'Sphyraena qenie',
    category: 'fish', habitat: ['ocean', 'reef'],
    description: 'Le barracuda forme des bancs impressionnants de centaines d\'individus dans les passes de Rangiroa.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Sphyraena_qenie.jpg/1200px-Sphyraena_qenie.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Sphyraena_qenie.jpg/400px-Sphyraena_qenie.jpg',
    conservation_status: 'LC', is_endemic: false,
    fun_fact: 'Les bancs de barracudas forment des tornades pour confondre les prédateurs.',
    locations: [{ id: 'l11', species_id: '8', latitude: -14.9950, longitude: -147.6323, name: 'Tiputa Pass' }],
    inaturalist_id: 80285, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '9', name_common_fr: 'Requin Marteau', name_common_en: 'Scalloped Hammerhead', name_scientific: 'Sphyrna lewini',
    category: 'shark', habitat: ['ocean'],
    description: 'Reconnaissable à sa tête en forme de T, il forme des bancs dans les eaux profondes autour de l\'atoll.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Scalloped_hammerhead_shark.jpg/1200px-Scalloped_hammerhead_shark.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Scalloped_hammerhead_shark.jpg/400px-Scalloped_hammerhead_shark.jpg',
    conservation_status: 'CR', is_endemic: false,
    fun_fact: 'La forme en marteau améliore le champ de vision et les capacités sensorielles électriques.',
    locations: [{ id: 'l12', species_id: '9', latitude: -14.9950, longitude: -147.6323, name: 'Tiputa Pass' }],
    inaturalist_id: 43961, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '10', name_common_fr: 'Poisson-Coffre Bleu', name_common_en: 'Blue Spotted Boxfish', name_scientific: 'Ostracion cyanurus',
    category: 'fish', habitat: ['reef', 'lagoon'],
    description: 'Sa forme hexagonale rigide lui vaut son nom et lui sert d\'armure naturelle.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ostracion_cyanurus.jpg/1200px-Ostracion_cyanurus.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ostracion_cyanurus.jpg/400px-Ostracion_cyanurus.jpg',
    conservation_status: 'LC', is_endemic: false,
    fun_fact: 'En cas de stress, le poisson-coffre sécrète des toxines qui peuvent tuer les autres poissons.',
    locations: [{ id: 'l13', species_id: '10', latitude: -14.9700, longitude: -147.7500, name: 'Lagon Bleu' }],
    inaturalist_id: 56487, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '11', name_common_fr: 'Baliste Picasso', name_common_en: 'Picasso Triggerfish', name_scientific: 'Rhinecanthus aculeatus',
    category: 'fish', habitat: ['reef'],
    description: 'Territorial, il défend agressivement son nid. Ses couleurs rappellent les tableaux de Picasso.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Rhinecanthus_aculeatus.jpg/1200px-Rhinecanthus_aculeatus.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Rhinecanthus_aculeatus.jpg/400px-Rhinecanthus_aculeatus.jpg',
    conservation_status: 'LC', is_endemic: false,
    fun_fact: 'Le baliste peut bloquer son épine dorsale dans les anfractuosités pour se protéger.',
    locations: [{ id: 'l14', species_id: '11', latitude: -15.0100, longitude: -147.7000, name: 'Avatoru Pass' }],
    inaturalist_id: 57234, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '12', name_common_fr: 'Frégate Superbe', name_common_en: 'Magnificent Frigatebird', name_scientific: 'Fregata magnificens',
    category: 'bird', habitat: ['coastal', 'ocean'],
    description: 'Grand oiseau marin planant au-dessus du lagon. Le mâle gonfle sa poche gulaire rouge.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Fregata_magnificens_1.jpg/1200px-Fregata_magnificens_1.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Fregata_magnificens_1.jpg/400px-Fregata_magnificens_1.jpg',
    conservation_status: 'LC', is_endemic: false,
    fun_fact: 'La frégate chipe souvent la nourriture d\'autres oiseaux en plein vol.',
    locations: [{ id: 'l15', species_id: '12', latitude: -15.0000, longitude: -147.7000, name: 'Avatoru Village' }],
    inaturalist_id: 4849, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '13', name_common_fr: 'Noddi Brun', name_common_en: 'Brown Noddy', name_scientific: 'Anous stolidus',
    category: 'bird', habitat: ['coastal', 'ocean'],
    description: 'Niche en colonies sur les cocotiers. Reconnaissable à sa calotte blanche.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Anous_stolidus.jpg/1200px-Anous_stolidus.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Anous_stolidus.jpg/400px-Anous_stolidus.jpg',
    conservation_status: 'LC', is_endemic: false,
    fun_fact: 'Contrairement aux autres sternes, le noddi brun se nourrit en surface plutôt qu\'en plongeant.',
    locations: [{ id: 'l16', species_id: '13', latitude: -14.9700, longitude: -147.7500, name: 'Lagon Bleu' }],
    inaturalist_id: 4855, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '14', name_common_fr: 'Crabe de Cocotier', name_common_en: 'Coconut Crab', name_scientific: 'Birgus latro',
    category: 'invertebrate', habitat: ['land', 'coastal'],
    description: 'Le plus grand arthropode terrestre du monde. Peut peser jusqu\'à 4 kg. Espèce nocturne protégée.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Coconut_crab.jpg/1200px-Coconut_crab.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Coconut_crab.jpg/400px-Coconut_crab.jpg',
    conservation_status: 'VU', is_endemic: false,
    fun_fact: 'Le crabe de cocotier peut vivre plus de 60 ans et ses pinces exercent une force de 3300 Newtons.',
    locations: [{ id: 'l17', species_id: '14', latitude: -14.9800, longitude: -147.7200, name: 'Île intérieure' }],
    inaturalist_id: 82728, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '15', name_common_fr: 'Cocotier', name_common_en: 'Coconut Palm', name_scientific: 'Cocos nucifera',
    category: 'plant', habitat: ['land', 'coastal'],
    description: 'Arbre symbole de la Polynésie. Omniprésent sur l\'atoll, il a nourri ses habitants pendant des siècles.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Coconut_tree_on_beach.jpg/1200px-Coconut_tree_on_beach.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Coconut_tree_on_beach.jpg/400px-Coconut_tree_on_beach.jpg',
    conservation_status: 'LC', is_endemic: false,
    fun_fact: 'Toutes les parties du cocotier sont utilisables : feuilles, tronc, fibre, eau, coprah, fleurs.',
    locations: [{ id: 'l18', species_id: '15', latitude: -15.0000, longitude: -147.7000, name: 'Partout sur l\'atoll' }],
    inaturalist_id: 57659, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '16', name_common_fr: 'Pandanus', name_common_en: 'Screw Pine', name_scientific: 'Pandanus tectorius',
    category: 'plant', habitat: ['land', 'coastal'],
    description: 'Plante iconique des atolls polynésiens. Ses feuilles servent à la fabrication de nattes et chapeaux.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Pandanus_tectorius_Kauai.jpg/1200px-Pandanus_tectorius_Kauai.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Pandanus_tectorius_Kauai.jpg/400px-Pandanus_tectorius_Kauai.jpg',
    conservation_status: 'LC', is_endemic: false,
    fun_fact: 'Les racines aériennes du pandanus l\'empêchent de tomber sur les zones instables.',
    locations: [{ id: 'l19', species_id: '16', latitude: -15.0200, longitude: -147.6800, name: 'Zone côtière' }],
    inaturalist_id: 55773, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '17', name_common_fr: 'Corail Cerveau', name_common_en: 'Brain Coral', name_scientific: 'Platygyra daedalea',
    category: 'coral', habitat: ['reef'],
    description: 'Ses canaux sinueux ressemblent à un cerveau humain. Ces formations peuvent vivre des centaines d\'années.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Platygyra_daedalea.jpg/1200px-Platygyra_daedalea.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Platygyra_daedalea.jpg/400px-Platygyra_daedalea.jpg',
    conservation_status: 'VU', is_endemic: false,
    fun_fact: 'Un corail cerveau de 2 mètres de diamètre peut avoir plus de 900 ans.',
    locations: [{ id: 'l20', species_id: '17', latitude: -15.0100, longitude: -147.7000, name: 'Avatoru Pass' }],
    inaturalist_id: 138367, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '18', name_common_fr: 'Poisson-Clown de Clark', name_common_en: "Clark's Anemonefish", name_scientific: 'Amphiprion clarkii',
    category: 'fish', habitat: ['reef'],
    description: 'Vit en symbiose avec les anémones dont il est immunisé contre les tentacules urticants.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Amphiprion_clarkii.jpg/1200px-Amphiprion_clarkii.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Amphiprion_clarkii.jpg/400px-Amphiprion_clarkii.jpg',
    conservation_status: 'LC', is_endemic: false,
    fun_fact: 'Le poisson-clown est hermaphrodite : le mâle dominant peut devenir femelle si la femelle disparait.',
    locations: [{ id: 'l21', species_id: '18', latitude: -14.9700, longitude: -147.7500, name: 'Lagon Bleu' }],
    inaturalist_id: 51873, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '19', name_common_fr: 'Requin Pointe Blanche', name_common_en: 'Whitetip Reef Shark', name_scientific: 'Triaenodon obesus',
    category: 'shark', habitat: ['lagoon', 'reef'],
    description: 'Le requin le plus commun du lagon de Rangiroa. Souvent observé au repos sur le fond.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Triaenodon_obesus.jpg/1200px-Triaenodon_obesus.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Triaenodon_obesus.jpg/400px-Triaenodon_obesus.jpg',
    conservation_status: 'VU', is_endemic: false,
    fun_fact: 'Le requin pointe blanche peut se reposer sur le fond sans s\'asphyxier.',
    locations: [{ id: 'l22', species_id: '19', latitude: -14.9700, longitude: -147.7500, name: 'Lagon Bleu' }],
    inaturalist_id: 43981, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '20', name_common_fr: 'Bénitier Géant', name_common_en: 'Giant Clam', name_scientific: 'Tridacna gigas',
    category: 'invertebrate', habitat: ['reef', 'lagoon'],
    description: 'Le plus grand mollusque bivalve du monde. Ses manteaux irisés résultent d\'algues symbiotes.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Tridacna_gigas.jpg/1200px-Tridacna_gigas.jpg',
    thumbnail_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Tridacna_gigas.jpg/400px-Tridacna_gigas.jpg',
    conservation_status: 'VU', is_endemic: false,
    fun_fact: 'Un bénitier géant peut vivre plus de 100 ans et peser jusqu\'à 250 kg.',
    locations: [{ id: 'l23', species_id: '20', latitude: -14.9700, longitude: -147.7500, name: 'Lagon Bleu' }],
    inaturalist_id: 49884, created_at: '2024-01-01T00:00:00Z',
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  fish: 'Poissons', shark: 'Requins', ray: 'Raies', mammal: 'Mammifères & Tortues',
  bird: 'Oiseaux', invertebrate: 'Invertébrés', plant: 'Flore', coral: 'Coraux',
};

export const CONSERVATION_LABELS: Record<string, string> = {
  LC: 'Préoccupation mineure', NT: 'Quasi menacé', VU: 'Vulnérable', EN: 'En danger',
  CR: 'En danger critique', EW: 'Éteint à l\'état sauvage', EX: 'Éteint', DD: 'Données insuffisantes',
};

export const CONSERVATION_COLORS: Record<string, string> = {
  LC: '#2E7D32', NT: '#558B2F', VU: '#F57F17', EN: '#E65100', CR: '#B71C1C', EW: '#4A148C', EX: '#212121', DD: '#546E7A',
};
